# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desing.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 930)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background: #333;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AppName = QtWidgets.QLabel(self.centralwidget)
        self.AppName.setGeometry(QtCore.QRect(220, 0, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.AppName.setFont(font)
        self.AppName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName.setStyleSheet("color:white; padding: 10px;")
        self.AppName.setObjectName("AppName")
        self.btnSelectImg = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectImg.setGeometry(QtCore.QRect(120, 580, 211, 41))
        self.btnSelectImg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSelectImg.setStyleSheet("color: #fff")
        self.btnSelectImg.setObjectName("btnSelectImg")
        self.UrlToImage = QtWidgets.QTextEdit(self.centralwidget)
        self.UrlToImage.setGeometry(QtCore.QRect(120, 700, 571, 91))
        self.UrlToImage.setStyleSheet("color:#fff")
        self.UrlToImage.setObjectName("UrlToImage")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(120, 110, 571, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:  #fff; ")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(40, 40, 112, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 40, 112, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(450, 40, 112, 23))
        self.radioButton_3.setStyleSheet("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.usa_icon = QtWidgets.QLabel(self.groupBox)
        self.usa_icon.setGeometry(QtCore.QRect(100, 40, 24, 24))
        self.usa_icon.setObjectName("usa_icon")
        self.rus_icon = QtWidgets.QLabel(self.groupBox)
        self.rus_icon.setGeometry(QtCore.QRect(300, 40, 24, 24))
        self.rus_icon.setObjectName("rus_icon")
        self.ukr_icon = QtWidgets.QLabel(self.groupBox)
        self.ukr_icon.setGeometry(QtCore.QRect(510, 40, 24, 24))
        self.ukr_icon.setObjectName("ukr_icon")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(120, 210, 571, 351))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.photo.setFont(font)
        self.photo.setStyleSheet("color: #fff; padding: 30; border: 2px dotted #fff; border-radius: 10px")
        self.photo.setScaledContents(True)
        self.photo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.photo.setObjectName("photo")
        self.btnCopy = QtWidgets.QPushButton(self.centralwidget)
        self.btnCopy.setGeometry(QtCore.QRect(120, 810, 211, 41))
        self.btnCopy.setStyleSheet("color: #fff;")
        self.btnCopy.setObjectName("btnCopy")
        self.successCopy = QtWidgets.QLabel(self.centralwidget)
        self.successCopy.setGeometry(QtCore.QRect(350, 810, 141, 41))
        self.successCopy.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.successCopy.setStyleSheet("padding:10px; border: 3px solid green; border-radius: 5px; color: green; align: center")
        self.successCopy.setInputMethodHints(QtCore.Qt.ImhNone)
        self.successCopy.setObjectName("successCopy")
        self.photo_icon = QtWidgets.QLabel(self.centralwidget)
        self.photo_icon.setGeometry(QtCore.QRect(220, 250, 371, 221))
        self.photo_icon.setStyleSheet("")
        self.photo_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_icon.setObjectName("photo_icon")
        self.dont_language = QtWidgets.QLabel(self.centralwidget)
        self.dont_language.setGeometry(QtCore.QRect(350, 580, 211, 41))
        self.dont_language.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dont_language.setStyleSheet("padding:10px; border: 3px solid red; border-radius: 5px; color: red; align: center")
        self.dont_language.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dont_language.setObjectName("dont_language")
        self.wrongExtension = QtWidgets.QLabel(self.centralwidget)
        self.wrongExtension.setGeometry(QtCore.QRect(120, 630, 571, 51))
        self.wrongExtension.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wrongExtension.setStyleSheet("padding:10px; border: 3px solid red; border-radius: 5px; color: red; align: center")
        self.wrongExtension.setInputMethodHints(QtCore.Qt.ImhNone)
        self.wrongExtension.setObjectName("wrongExtension")
        self.btnTranslate = QtWidgets.QPushButton(self.centralwidget)
        self.btnTranslate.setGeometry(QtCore.QRect(510, 810, 181, 41))
        self.btnTranslate.setStyleSheet("color: #fff;")
        self.btnTranslate.setObjectName("btnTranslate")
        self.listHistory = QtWidgets.QListWidget(self.centralwidget)
        self.listHistory.setGeometry(QtCore.QRect(950, 80, 511, 141))
        self.listHistory.setObjectName("listHistory")
        self.listHistoryOld = QtWidgets.QListWidget(self.centralwidget)
        self.listHistoryOld.setGeometry(QtCore.QRect(950, 320, 511, 141))
        self.listHistoryOld.setObjectName("listHistoryOld")
        self.Last10Header = QtWidgets.QLabel(self.centralwidget)
        self.Last10Header.setGeometry(QtCore.QRect(1100, 250, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Last10Header.setFont(font)
        self.Last10Header.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Last10Header.setStyleSheet("color:white; padding: 10px;")
        self.Last10Header.setObjectName("Last10Header")
        self.ThisSessionHeader = QtWidgets.QLabel(self.centralwidget)
        self.ThisSessionHeader.setGeometry(QtCore.QRect(1060, 10, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ThisSessionHeader.setFont(font)
        self.ThisSessionHeader.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThisSessionHeader.setStyleSheet("color:white; padding: 10px;")
        self.ThisSessionHeader.setObjectName("ThisSessionHeader")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(920, 500, 571, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color:  #fff; ")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(40, 40, 112, 23))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_8.setGeometry(QtCore.QRect(240, 40, 112, 23))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_9.setGeometry(QtCore.QRect(450, 40, 112, 23))
        self.radioButton_9.setStyleSheet("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.usa_icon_3 = QtWidgets.QLabel(self.groupBox_2)
        self.usa_icon_3.setGeometry(QtCore.QRect(100, 40, 24, 24))
        self.usa_icon_3.setObjectName("usa_icon_3")
        self.rus_icon_3 = QtWidgets.QLabel(self.groupBox_2)
        self.rus_icon_3.setGeometry(QtCore.QRect(300, 40, 24, 24))
        self.rus_icon_3.setObjectName("rus_icon_3")
        self.ukr_icon_3 = QtWidgets.QLabel(self.groupBox_2)
        self.ukr_icon_3.setGeometry(QtCore.QRect(510, 40, 24, 24))
        self.ukr_icon_3.setObjectName("ukr_icon_3")
        self.dont_language_2 = QtWidgets.QLabel(self.centralwidget)
        self.dont_language_2.setGeometry(QtCore.QRect(950, 800, 511, 41))
        self.dont_language_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dont_language_2.setStyleSheet("padding:10px; border: 3px solid red; border-radius: 5px; color: red; text-align: center")
        self.dont_language_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dont_language_2.setObjectName("dont_language_2")
        self.translateField = QtWidgets.QTextEdit(self.centralwidget)
        self.translateField.setGeometry(QtCore.QRect(920, 600, 571, 161))
        self.translateField.setStyleSheet("color:#fff")
        self.translateField.setObjectName("translateField")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AppName.setText(_translate("MainWindow", "Image_to_string"))
        self.btnSelectImg.setText(_translate("MainWindow", "SELECT IMAGE"))
        self.groupBox.setTitle(_translate("MainWindow", "                                         SELECT LANGUAGE"))
        self.radioButton.setText(_translate("MainWindow", "eng"))
        self.radioButton_2.setText(_translate("MainWindow", "rus"))
        self.radioButton_3.setText(_translate("MainWindow", "ukr"))
        self.usa_icon.setText(_translate("MainWindow", "usa"))
        self.rus_icon.setText(_translate("MainWindow", "rus"))
        self.ukr_icon.setText(_translate("MainWindow", "ukr"))
        self.photo.setText(_translate("MainWindow", "YOUR IMAGE"))
        self.btnCopy.setText(_translate("MainWindow", "COPY TEXT"))
        self.successCopy.setText(_translate("MainWindow", "SUCCESS COPY!"))
        self.photo_icon.setText(_translate("MainWindow", "TextLabel"))
        self.dont_language.setText(_translate("MainWindow", "DON\'T SELECT LANGUAGE"))
        self.wrongExtension.setText(_translate("MainWindow", "WRONG EXTENSION. ENABLE EXTENSIONS: png, jpeg, jpg"))
        self.btnTranslate.setText(_translate("MainWindow", "TRANSLATE"))
        self.Last10Header.setText(_translate("MainWindow", "LAST 10 IMAGES"))
        self.ThisSessionHeader.setText(_translate("MainWindow", "IMAGES IN THIS SESSION"))
        self.groupBox_2.setTitle(_translate("MainWindow", "                         SELECT LANGUAGE FOR TRANSLATE"))
        self.radioButton_7.setText(_translate("MainWindow", "eng"))
        self.radioButton_8.setText(_translate("MainWindow", "rus"))
        self.radioButton_9.setText(_translate("MainWindow", "ukr"))
        self.usa_icon_3.setText(_translate("MainWindow", "usa"))
        self.rus_icon_3.setText(_translate("MainWindow", "rus"))
        self.ukr_icon_3.setText(_translate("MainWindow", "ukr"))
        self.dont_language_2.setText(_translate("MainWindow", "DON\'T SELECT LANGUAGE"))
